[build]
  base = "/"
  publish = "apps/frontend/dist"
  command = "cd apps/frontend && npm install && npm run build:ci"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
