[build]
  base = "/"
  publish = "dist/apps/frontend"
  command = "npm ci && npx nx build frontend --configuration=ci"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
